"""Initial models

Revision ID: 11605f79cee6
Revises: 
Create Date: 2023-03-22 09:07:58.699423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11605f79cee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_table('schedule_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('datetime_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
