"""Deleted role_id

Revision ID: 2f136f59db3f
Revises: 11605f79cee6
Create Date: 2023-03-22 09:10:21.526268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f136f59db3f'
down_revision = '11605f79cee6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
